# -*- coding: utf-8 -*-
"""MovieRecommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rPxJY2956qtwHfb8ATzCy7P9iSRAB4XZ

Install Libraries
"""


"""Import Libraries"""

import streamlit as st
import openai
import requests
import os

"""Create a file to store API Keys"""

# Set your API keys here
openai.api_key = st.secrets["OPENAI_API_KEY"]
TMDB_API_KEY = st.secrets["TMDB_API_KEY"]


#Header
st.set_page_config(page_title="🎬 Mood-Based Movie Recommender", layout="wide")
st.title("🎬 Mood-Based Movie Recommender")
st.markdown("Tell us your mood, and get 3 movie suggestions — with posters!")



# User mood input
mood = st.text_input("How are you feeling right now?", placeholder="e.g. adventurous, sad, romantic")

if st.button("🎥 Get Movie Recommendations") and mood:
    with st.spinner("Generating recommendations..."):

        # Step 1: Ask OpenAI for movie ideas based on mood
        prompt = f"Recommend 3 movies that match the mood '{mood}'. For each movie, include the title in **bold** and a one-sentence description."

        try:
            client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": prompt}],
    temperature=0.7,
    max_tokens=500
)

ai_reply = response.choices[0].message.content.strip()

            # Step 2: Extract movie titles from the response
            import re
            movie_titles = re.findall(r"\*\*(.*?)\*\*", ai_reply)
            if not movie_titles:
                # fallback if bold titles not found
                movie_titles = [line.split(".")[1].strip().split("(")[0] for line in ai_reply.split("\n") if "." in line][:3]

            # Step 3: Use TMDB to fetch posters
            st.markdown("### 🎞 Posters")
            cols = st.columns(3)

            for i, title in enumerate(movie_titles):
                params = {
                    "api_key": TMDB_API_KEY,
                    "query": title
                }
                result = requests.get("https://api.themoviedb.org/3/search/movie", params=params).json()
                if result["results"]:
                    movie = result["results"][0]
                    poster_path = movie["poster_path"]
                    image_url = f"https://image.tmdb.org/t/p/w500{poster_path}" if poster_path else None
                    release_year = movie.get("release_date", "")[:4]

                    with cols[i]:
                        if image_url:
                            st.image(image_url, width=250)
                        st.markdown(f"**{title}** ({release_year})")
                else:
                    with cols[i]:
                        st.markdown(f"**{title}** – Poster not found.")

        except Exception as e:
            st.error(f"Something went wrong: {e}")
